name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - run: npm run install
      - name: Upload snapshots to percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: cd DesignSystem && yarn snapshot
      - name: build DesignSystem Federation
        run: yarn build:federation
      - name: build App
        run: cd ../App && yarn build
