name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - name: Upload snapshots to percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: cd DesignSystem && yarn snapshot
      - name: build DesignSystem Federation
        run: cd DesignSystem && yarn build:federation
      - name: build App
        run: cd App && yarn build
      - name: deploy to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: node ./scripts/deploy-to-s3.js
